// Generated by CoffeeScript 1.6.2
(function() {
  var socket;

  socket = io.connect('/');

  socket.on('connected', function(data) {
    return console.log('connected');
  });

  socket.on('news', function(data) {
    return console.log(data);
  });

}).call(this);
