// Generated by CoffeeScript 1.6.2
(function() {
  var app, io, server;

  app = require('express')();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  server.listen(8088);

  app.get('/', function(req, res) {
    return res.sendfile("" + __dirname + "/index.html");
  });

  app.get('/client.js', function(req, res) {
    return res.sendfile("" + __dirname + "/client.js");
  });

  io.sockets.on('connection', function(socket) {
    socket.emit('news', {
      hello: 'world'
    });
    return socket.on('my other event', function(data) {
      return console.log(data);
    });
  });

}).call(this);
